### ISSUE TITLE
Docker stack

### ISSUE THREAD

**Issue by muety** [techsneeze/dmarcts-report-parser#100]
Do you plan on dockerizing the application and providing a Docker Compose stack for parser, viewer and database all at once? This might help people get started more quickly, without having to install the Perl- and PHP dependencies and having a web server with FPM running.

Just an idea. If you'd like that, I'll look into it and do a PR. Otherwise feel free to just close this issue again.

**Comment by LaggAt** [comment]
Hi, have you seen this?
https://github.com/gutmensch/docker-dmarc-report

**Comment by rallisf1** [comment]
I only needed the parser dockerized, so I published it here: https://hub.docker.com/r/rallisf1/dmarcts-report-parser
