### ISSUE TITLE
Centos 7.1

### ISSUE THREAD

**Issue by Tntdruid** [techsneeze/dmarcts-report-parser#11]
Hello,

libmail-imapclient-perl libmime-tools-perl libxml-simple-perl 
libclass-dbi-mysql-perl libio-socket-inet6-perl libio-socket-ip-perl libperlio-gzip-perl

Is not avabel for Centos 7.1?

**Comment by techsneeze** [comment]
Correct.  Those are the instructions listed for Debian.  The packages are likely called something different on CentOS 7.1.  If you try to run the script it should tell you which Perl modules are missing, and you can work through finding the dependencies.  I don't have a CentOS 7.1 system to be able to tell you the exact packages you would need.  If I get access to one, I'll update this thread and the directions.

**Comment by techsneeze** [comment]
I was able to setup a test VM and it looks like the following should get the dependencies for you:

```
yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum install perl-Mail-IMAPClient perl-MIME-tools perl-XML-Simple perl-DBI \
 perl-Socket6 perl-PerlIO-gzip perl-DBD-MySQL
```

This will add the EPEL repo, and then install the dependencies.

**Comment by Tntdruid** [comment]
Works :)

Thanks so much!

**Comment by Tntdruid** [comment]
Use of uninitialized value in concatenation (.) or string at ./dmarcts-report-pa                                     rser.pl line 173.
There are  messages in the new folder.

There are 11 mail in the new dir, using cPanel whit Dovecot

**Comment by techsneeze** [comment]
I've tested that the script works on CentOS 7.1.  In the process I determined that you should also do:
`yum install unzip`
That shouldn't cause your problem, but would be a good idea.
Can you share what you have in your config file for:
$imapmovefolder
and
$imapreadfolder

My guess is the folder isn't being referenced correctly, and it isn't able to find it.

**Comment by Tntdruid** [comment]
Package unzip-6.0-15.el7.x86_64 already installed and latest version

$imapmovefolder = '.Processed';
$imapreadfolder = 'mail';

**Comment by techsneeze** [comment]
Try removing the "." before Processed.  

If the Processed is a subfolder of another folder you need to put the parent folder before the period.  For example, if it is a subfolder of Inbox, you would put "Inbox.Processed".  

Does that fix it?

**Comment by Tntdruid** [comment]
still get
root@asgard [~/dmarcts-report-parser]# ./dmarcts-report-parser.pl -d
Use of uninitialized value in concatenation (.) or string at ./dmarcts-report-parser.pl line 173.
There are  messages in the mail folder.

If i make a new folder in webmail it auto get . in the start of the dir name
![flashfxp_2016-03-21_14-13-42](https://cloud.githubusercontent.com/assets/72948/13919667/26fd5482-ef6f-11e5-8600-2cf2286f4a2d.png)

**Comment by techsneeze** [comment]
That looks like the raw filesystem, but you seem to be trying to connect with IMAP.  What do the folder names look like in webmail or via an IMAP client?  Does it show the "." at the front?

**Comment by Tntdruid** [comment]
In webmail its show as Processed, test it whit just Processed same problem. says no new msg's

**Comment by techsneeze** [comment]
OK, so I think I was focused on the wrong folder.  We need to read the mail before we worry about where it gets moved! :-)  I'm guessing you'll still need to remove the "." for the imapmovefolder.

Try changing the imapreadfolder to:
`$imapreadfolder = 'Inbox';
`
That is what I use with my Dovecot IMAP server.  I then move to:

`$imapmovefolder = 'processed';
`
You will likely want to capitalize it for your setup, to "Processed".

**Comment by Tntdruid** [comment]
Works now :)

Thanks for the help
