### ISSUE TITLE
Not working under FreeBSD 14.1 and MariaDB server for database

### ISSUE THREAD

**Issue by gnomii** [techsneeze/dmarcts-report-parser#125]
Hello,

I update my FreeBSD 13.1 to 14.1 and the package used to connect to MariaDB database was p5-DBD-MySQL. After the update, the package is p5-DBD-MariaDB.

I have this error :
<pre>
Use of uninitialized value $dbhost in concatenation (.) or string at /usr/local/bin/dmarcts-report-parser.pl line 273.
install_driver(mysql) failed: Can't locate DBD/mysql.pm in @INC (you may need to install the DBD::mysql module) (@INC contains: /usr/local/lib/perl5/site_perl/mach/5.36 /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.36/mach /usr/local/lib/perl5/5.36) at (eval 115) line 3.
Perhaps the DBD::mysql perl module hasn't been fully installed,
or perhaps the capitalisation of 'mysql' isn't right.
Available drivers: DBM, ExampleP, File, Gofer, MariaDB, Mem, Proxy, Sponge.
</pre>

If I set "MariaDB" for dbtype in dmarcts-report-parser.conf I have this error : 
<pre>
dmarcts-report-parser.pl: couldn't load DB definition for type MariaDB: No such file or directory at /usr/local/bin/dmarcts-report-parser.pl line 271.
</pre>

To fix the error, I copied the file /usr/local/share/dmarcts-report-parser/dbx_mysql.pl to /usr/local/share/dmarcts-report-parser/dbx_MariaDB.pl.

Is it possible to update the project to able to use the MariaDB database ?

**Comment by dgeo** [comment]
In the meantime you can use p5-DBD-mysql4 instead (DBD::mysql v5+ is not compatible with mariadb)
see https://cgit.freebsd.org/ports/commit/?id=7915eb5cbe18153b51601e2b524e96363daf067c

But being able to use DBD::MariaDB here is the right thing to do IMHO ;)

**Comment by gnomii** [comment]
Well seen ! I reinstall the p5-DBD-mysql v4 and it's working.

Thanks you
