### ISSUE TITLE
ignore invalid certificate

### ISSUE THREAD

**Issue by celevra** [techsneeze/dmarcts-report-parser#14]
Hi,

is there a switch to ignore an invalid ssl cert?
I get this error:

```
IMAP Failure: Unable to start TLS: SSL connect attempt failed with unknown error error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed at ./dmarcts-report-parser.pl line 154.
```

regards

**Comment by techsneeze** [comment]
Hmm.  That is not a case that is currently covered.  I could look at adding it in the future, but it wouldn't be in the near future.  If you were able to put together a pull request, we could look at adding it in sooner.

Regardless...

I tried to test the situation in my environment, by using a different hostname than the certificate, but that still worked without error for me.  I suspect that your cert is self-signed?

In the scripts current state, I'd see a few options with varying degrees of desirability...
- Add the cert info to the machine running the script, so the machine is generally trusting the cert.  You would probably need to add the self-signed certs root CA to your machine.  The script should then trust the cert as well.
- Try using the SSL mode in the configuration file, and changing the port to 993

```
$imaptls = '0' ;
$imapssl = '1';
$imapserver = 'mail.example.com:993';
```
- Disable TLS in the configuration file with `$imaptls = '0';`.  The encryption path can't be trusted anyways, due to man-in-the-middle, etc.

**Comment by celevra** [comment]
thanks for the fast answer.
if tried to change the code like that:

```
        # Setup connection to IMAP server.
        my $imap = Mail::IMAPClient->new( Server => $imapserver,
                Ssl => $imapssl,
                debug => 1)
        # module uses eval, so we use $@ instead of $!
        or die "IMAP Failure: $@";

        if ($imaptls) {
                $imap->starttls
                (
                    SSL_verify_mode => 0,
                ) or die "starttls failed: $@\n";
        }

        $imap->User($imapuser);
        $imap->Password($imappass);

        $imap->login() or die "IMAP Failure: $@";
```

but it doesn't work at all. 
yes i have a self signed certificate, but without an ca, output of openssl:

```
mailer dmarcts-report-parser # openssl s_client -crlf -connect 192.168.5.2:993
CONNECTED(00000003)
depth=0 CN = exchange
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = exchange
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/CN=exchange
   i:/CN=exchange
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDEjCCAfqgAwIBAgIQFYR6hOZvGZJBT7kEEnRJHzANBgkqhkiG9w0BAQUFADAT
MREwDwYDVQQDEwhleGNoYW5nZTAeFw0xNTEyMzEwMDQ5NDlaFw0yMDEyMzEwMDQ5
NDlaMBMxETAPBgNVBAMTCGV4Y2hhbmdlMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAs87ScneMbnh1wOhPckY3nalsV6s9rNCUkL1cJC8UzGh8DwJ3PpN2
9ml/ZBch7Qn2qyA9AKNrhQg4O9FSJsBnFeMTp0XQdO9Tmt8H8iQwR8O+9CC4y9S6
//iMVaroDrQp6ClncYWpiB0zaSMdD0F/gKcRTIWfyMCmFb5/7/qyRJ5gZvZUYJsY
t9aHzFiwzr9CqqBZ7n8CjWrsyRk/qgG7XqJCNHdEdFrcYvMtVcI/6qG66hH7/1Gz
uAaa6HX/YA+vgHT1hh8FZptWvTH5c9uvawTWi0d89cQgm+sApZiYR5mUWLN92HyQ
aCqruGFwzKi9y9mWMxnpgSuj1e+tC0IRpQIDAQABo2IwYDAOBgNVHQ8BAf8EBAMC
BaAwKwYDVR0RBCQwIoIIZXhjaGFuZ2WCFmV4Y2hhbmdlLnplaXRzY2hlbC5uZXQw
EwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADANBgkqhkiG9w0BAQUF
AAOCAQEATr5RHY+RC2QozQfJLwgljFWicuvzXmkxgQ81vcikDRqplfGl6si2Mbri
2t0SFcI7ddg0mH9FVFEl5yIXv0PRzTGyOFuxZ/4eACyZHqLppn12ZOML1mCNhmAs
6pdQ48KFqtTacjJKEBmLnCmlNzEREoRVHwUSKon2f6ctoLsLpsmiejpZ1DHaFuRR
f1leVWr0ANCzekH7SvG4oqcPpqz+O9pT5+dsThuXNFGAmZxowuYzwjZ//z+yY7zv
tH6zxmuc3ACqBkOmM/L1C7+3mno4itD9LiFODnibbtIlqW2qSvrzvq8j+BuzUS8p
6i1p+SGDPappL0WFBD5yABCH3MzjRw==
-----END CERTIFICATE-----
subject=/CN=exchange
issuer=/CN=exchange
---
No client certificate CA names sent
---
SSL handshake has read 1362 bytes and written 509 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-SHA384
    Session-ID: 4E190000D258EBF979E250657EF472FB102EADF77C0A25B61FF716526150CB3D
    Session-ID-ctx:
    Master-Key: 4C9BC61AFC19EA1E5AFAF20CF55556E4F5DFC4F351FF262142E4D408110181B04DFD6F3F7E10B89247DB82976D6C41E9
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1459502143
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)
---
* OK The Microsoft Exchange IMAP4 service is ready.
^C
mailer dmarcts-report-parser #
```

if i change tls to 0 and ssl to 1 and change the port to 993 i get also an error:

```
IMAP Failure: Unable to connect to 192.168.5.2:993:  at ./dmarcts-report-parser.pl line 156.
```

but that is not possible because openssl is able to connect...

i will dig a little bit more, any more ideas from your side?

**Comment by techsneeze** [comment]
I just submitted a change that fixed a somewhat related error, as seen in #15 .  

Can you pull the latest changes and see if it fixes your problem too?

**Comment by celevra** [comment]
hm the change looks good and could be the reason why my code change with SSL_verify_mode haven't worked. Unfurtunately i can't test it anymore, i have installed a valid cert as my workaround.
I will look if i found time to install a fast dev env with an imap server to test the new code.

**Comment by celevra** [comment]
faster as i thought, i have an second imap server laying around.
but unfortunately i get the same error.
```
IMAP Failure: Unable to start TLS: SSL connect attempt failed with unknown error error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol at ./dmarcts-report-parser.pl line 161.
```

**Comment by celevra** [comment]
faster as i tought. I have another imapserver laying around. works like a charme!
Thanks for the fast fix, also when i don't need it anymore :-D

another thing, i get the mails from an exchange server. And here i got many errors that the size of the mail is not correct, so i had to add IgnoreSizeErrors => 1 in the Mail::IMAPClient constructor on line 167

**Comment by techsneeze** [comment]
I'm glad that it cleared up your issue... even if you don't need it anymore! :)

Thanks for the tip about IgnoreSizeErrors.  I'll have to investigate that option, and see if we should add it as a default or configurable option.
