### ISSUE TITLE
IMAP Failure: 1 BAD Command received in Invalid state

### ISSUE THREAD

**Issue by wioxjk** [techsneeze/dmarcts-report-parser#25]
Hi,

I am fairly new to DMARC and perl, so when this appear I feel totally lost.
The .conf file looks as `this:`

> $debug = 0;
> $delete_reports = 0;
> 
> $dbname = 'dmarc_mots_local';
> $dbuser = 'dmarc_mots_local';
> $dbpass = '4gj47ryO';
> $dbhost = 'localhost'; # Set the hostname if we can't connect to the local socket.
> 
> $imapserver = 'mailserver:993';
> $imapuser = 'user';
> $imappass = 'password';
> $imapssl = '1'; # If set to 1, remember to change server port to 993.
> $imaptls = '1'; # Enabled as the default and best-practice.
> $imapreadfolder = 'Inbox';
>
> $imapmovefolder = 'Inbox.processed';
> 
> $maxsize_xml = 50000;
> $compress_xml = 0;
> $delete_failed = 0;

The error message I get when I try to run the .pl file:

>IMAP Failure: 1 BAD Command received in Invalid state. at ./dmarcts-report-parser.pl line 185.

**Comment by lwt-pressy** [comment]
The error occurs while connecting to your mail server. Try turning on debug and look in the logfiles of your mailserver. Check also your login and password and ssl/tls options. For helping you should also say what mailserver you use.

**Comment by wioxjk** [comment]
@lwt-pressy 
Thanks. For some reason, the server lock the user when I try to connect with it. That problem is now solved.
I am running Exchange 2013.
