### ISSUE TITLE
Could not create IMAP folder: Inbox.processed

### ISSUE THREAD

**Issue by wioxjk** [techsneeze/dmarcts-report-parser#33]
I am having theese issues when running `./dmarcts-report-parser.pl -i`

```
Already have emailsrvr.com a71202c5-d108-40bf-a818-6252fc01fb16, skipped
Could not create IMAP folder: Inbox.processed.
Error on moving (copy and delete) processed IMAP message: Could not COPY message to IMAP folder: <Inbox.processed>!
Messsage will not be moved/deleted. [11 NO [CANNOT] Character not allowed in mailbox name: '.']
```

No logs are generated on the mailserver,
I am quite clueless here :)

**Comment by lwt-pressy** [comment]
basically it cannot create the folder "processed" in your inbox where it wants to store the processed reports. You could try creating the folder manually, that should probally work. Which imap server do you use?

**Comment by techsneeze** [comment]
You could also try changing your configuration from "Inbox.processed" to just "processed".  It looks like your IMAP server doesn't want a "." in the folder name.  Some IMAP servers use that to note subfolders.

**Comment by wioxjk** [comment]
I already have created an folder called processed, but my inbox is named INBOX - does that matter?

I use my own imap server, iRedmail
![image](https://user-images.githubusercontent.com/10996038/28590201-9aaff034-7181-11e7-85a9-ae1c9e0c2c7f.png)

**Comment by wioxjk** [comment]
> You could also try changing your configuration from "Inbox.processed" to just "processed". It looks like your IMAP server doesn't want a "." in the folder name. Some IMAP servers use that to note subfolders.


Thanks, that does work! :)

**Comment by lwt-pressy** [comment]
based on [http://www.iredmail.org/docs/public.folder.html](http://www.iredmail.org/docs/public.folder.html)  iredmail uses dovecot as imap backend with config of "/" as seperator/delimiter instead of ".". Perhaps we could read the delimiter bei [http://php.net/manual/en/function.imap-getmailboxes.php](http://php.net/manual/en/function.imap-getmailboxes.php).
