### ISSUE TITLE
[MariaDB] DBD::mysql::db do failed: Specified key was too long

### ISSUE THREAD

**Issue by EnochTheWise** [techsneeze/dmarcts-report-parser#34]
`DBD::mysql::db do failed: Specified key was too long; max key length is 767 bytes at ./dmarcts-report-parser.pl line 816. Use of uninitialized value in concatenation (.) or string at ./dmarcts-report-parser.pl line 233.`

Full output: https://pastebin.com/2hLCL3eR

**Comment by lwt-pressy** [comment]
probably associated with [https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes](https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes).

**Comment by EnochTheWise** [comment]
I solved the problem with the index, by change:
collation_server=utf8_unicode_ci
character_set_server=utf8
