### ISSUE TITLE
Perl Error

### ISSUE THREAD

**Issue by Tntdruid** [techsneeze/dmarcts-report-parser#36]
`./dmarcts-report-parser.pl
Can't locate Mail/Mbox/MessageParser.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./dmarcts-report-parser.pl line 64.
BEGIN failed--compilation aborted at ./dmarcts-report-parser.pl line 64.
`
Using CentOS 7

Package perl-Mail-IMAPClient-3.37-1.el7.noarch already installed and latest version
Package perl-MIME-tools-5.505-1.el7.noarch already installed and latest version
Package perl-XML-Simple-2.20-5.el7.noarch already installed and latest version
Package perl-DBI-1.627-4.el7.x86_64 already installed and latest version
Package perl-Socket6-0.23-15.el7.x86_64 already installed and latest version
Package perl-PerlIO-gzip-0.19-1.el7.x86_64 already installed and latest version
Package perl-DBD-MySQL-4.023-5.el7.x86_64 already installed and latest version
Package unzip-6.0-16.el7.x86_64 already installed and latest version
Nothing to do

I'm missing some perl stuff?

**Comment by techsneeze** [comment]
Please try installing perl-Mail-Mbox-MessageParser 
That appears to be the package missing from your setup.

**Comment by Tntdruid** [comment]
Works now thanks, You should add that to the:

on CentOS (CentOS 7):

yum` install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum install perl-Mail-IMAPClient perl-MIME-tools perl-XML-Simple perl-DBI \
 perl-Socket6 perl-PerlIO-gzip perl-DBD-MySQL unzip perl-Mail-Mbox-MessageParser
