### ISSUE TITLE
Source IPv6 is not parsed (does not show up in the GUI)

### ISSUE THREAD

**Issue by wioxjk** [techsneeze/dmarcts-report-parser#37]
As the title says, if the "source ip" is an IPv6 address is does not get parsed and does not show up in the GUI.

**Comment by lwt-pressy** [comment]
@techsneeze - this is probably not an error on dmarcts-report-parser, but in dmarcts-report-viewer.  Should be fixed with PR  https://github.com/techsneeze/dmarcts-report-viewer/pull/21

**Comment by wioxjk** [comment]
@lwt-pressy 
Thanks, I willl take a look

**Comment by lwt-pressy** [comment]
The pr is already merge, so can update your version the normal way.
