### ISSUE TITLE
IMAP Failure: Unable to connect

### ISSUE THREAD

**Issue by BenKennish** [techsneeze/dmarcts-report-parser#38]
I cannot get the script to connect succesfully to imap.gmail.com:993.   I've edited the config file, have configured `$imapssl = '1'` and I have set `$debug = 1` but I only get the following output:

```
$ ./dmarcts-report-parser.pl -d -i
*******************************************************************
 Using the default of SSL_verify_mode of SSL_VERIFY_NONE for client
 is deprecated! Please set SSL_verify_mode to SSL_VERIFY_PEER
 together with SSL_ca_file|SSL_ca_path for verification.
 If you really don't want to verify the certificate and keep the
 connection open to Man-In-The-Middle attacks please set
 SSL_verify_mode explicitly to SSL_VERIFY_NONE in your application.
*******************************************************************
  at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 361.
IMAP Failure: Unable to connect to imap.gmail.com:993:  at ./dmarcts-report-parser.pl line 217.
```

Shouldn't debug mode be a bit more explicit than this?

I'm running on a freshly installed CentOS 7.3 Virtual Machine.  I have changed the setting on the GSuite account to "allow less secure apps".

I can connect ok manually from the VM using `openssl s_client`...

```
$ openssl s_client -connect imap.gmail.com:993 -crlf
CONNECTED(00000003)
..<snip>..
* OK Gimap ready for requests from 1.2.3.4 b9mb58885590wrb
a1 LOGIN user@example.com password_here
* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS LITERAL- SPECIAL-USE APPENDLIMIT=35651584
a1 OK user@example.com authenticated (Success)
a2 SELECT inbox
* FLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing)
* OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing \*)] Flags permitted.
* OK [UIDVALIDITY 1] UIDs valid.
* 8 EXISTS
* 0 RECENT
* OK [UIDNEXT 13] Predicted next UID.
* OK [HIGHESTMODSEQ 2171]
a2 OK [READ-WRITE] inbox selected. (Success)
a2 LOGOUT
* BYE LOGOUT Requested
a2 OK 73 good day (Success)
read:errno=0
```
Thanks in advance for any help you can provide

**Comment by lwt-pressy** [comment]
Could you please try the version from [https://github.com/lwt-pressy/dmarcts-report-parser.git](https://github.com/lwt-pressy/dmarcts-report-parser.git). I changed the tls handling hopefully to the new checkings by documentation, but my version is not showing the "deprecated" warning so i can't test it. Only that it still works. If it fixes it I make a pull request.

**Comment by BenKennish** [comment]
I get the same result using that version, including the deprecation warning 😞...

```
$ ./dmarcts-report-parser.pl -d -i
*******************************************************************
 Using the default of SSL_verify_mode of SSL_VERIFY_NONE for client
 is deprecated! Please set SSL_verify_mode to SSL_VERIFY_PEER
 together with SSL_ca_file|SSL_ca_path for verification.
 If you really don't want to verify the certificate and keep the
 connection open to Man-In-The-Middle attacks please set
 SSL_verify_mode explicitly to SSL_VERIFY_NONE in your application.
*******************************************************************
  at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 361.
IMAP Failure: Unable to connect to imap.gmail.com:993:  at ./dmarcts-report-parser.pl line 222.
```

**Comment by BenKennish** [comment]
Also would it be possible for dmarcts-report-parser to work without using `SSL_VERIFY_NONE`?  I'm concerned about MitM attacks that could result from using this mode

**Comment by lwt-pressy** [comment]
Based on my google searches could it be that your perl version is not up to date. If your  IO::Socket::SSL is < v2.037 this could produce the warning. But probably it has nothing to do with the error. As you use port 993 you use basic ssl and no tls, so you can set $imaptls = '0'; so ssl_verify_mode is not set and the perl default ist used. A new version uses  SSL_VERIFY_PEER. But I'm not sure, that this will soive the connect error and I don't know how to get more error message from the module so I can only advise to check the user / password settings.

**Comment by lwt-pressy** [comment]
Just after writing I found the imap debug flag. So now the version in my report also turns on the imap debugging. Perhaps we get some more info what goes wrong.

Something like below should appear:

> Using Mail::IMAPClient version 3.38 on perl 5.024001
> Connecting with IO::Socket::INET PeerAddr xxxxx:143 PeerPort 143 Proto tcp Timeout 600 Debug 1
> Connected to xxxxx:143
> Read:   * OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE STARTTLS LOGINDISABLED] xxxx Cyrus IMAP...

**Comment by BenKennish** [comment]
I've git pulled the latest version from your repo, set `$imaptls = '0';`, and set `$debug = 1;`.  Now when I run the script I get the following:

 ```
$ ./dmarcts-report-parser.pl -d -i
Started at Wed Aug 23 16:38:02 2017
Using Mail::IMAPClient version 3.37 on perl 5.016003
Connecting with IO::Socket::SSL PeerAddr imap.gmail.com:993 PeerPort 993 Proto tcp Timeout 600 Debug 1
*******************************************************************
 Using the default of SSL_verify_mode of SSL_VERIFY_NONE for client
 is deprecated! Please set SSL_verify_mode to SSL_VERIFY_PEER
 together with SSL_ca_file|SSL_ca_path for verification.
 If you really don't want to verify the certificate and keep the
 connection open to Man-In-The-Middle attacks please set
 SSL_verify_mode explicitly to SSL_VERIFY_NONE in your application.
*******************************************************************
  at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 361.
ERROR: Unable to connect to imap.gmail.com:993:  at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 370.
	Mail::IMAPClient::connect('Mail::IMAPClient=HASH(0x352cf10)') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 313
	Mail::IMAPClient::new('Mail::IMAPClient', 'Server', 'imap.gmail.com:993', 'Ssl', 1, 'Starttls', undef, 'User', 'user@example.com', ...) called at ./dmarcts-report-parser.pl line 224
IMAP Failure: Unable to connect to imap.gmail.com:993:  at ./dmarcts-report-parser.pl line 224.
```
Cheers,

**Comment by lwt-pressy** [comment]
sorry, im out of hints and have no google account.

**Comment by BenKennish** [comment]
ok thanks anyway

**Comment by astropsychic** [comment]
@BenKennish  any updates on the issue? was this resolved?

**Comment by BenKennish** [comment]
Unfortuately I didn't find a solution to the problem :disappointed:
