### ISSUE TITLE
parse_data: No data passed at ./dmarcts-report-parser.pl line 439.

### ISSUE THREAD

**Issue by SamosHaven** [techsneeze/dmarcts-report-parser#40]
I have followed the instructions in the guide on how to set up the report parser and I'm getting this error. 

**parse_data: No data passed at ./dmarcts-report-parser.pl line 439.**

Looks as though the pearl program has trouble recognizing the XML files that are stored in a ZIP file in my IMAP server email inbox. 

Anyone know of / can think of a fix for this problem.

Much appreciated.

**Comment by lwt-pressy** [comment]
@SamosHaven - could you please comment how your call dmarcte-report-parser.pl and give us an output with -d (debug) set.

**Comment by SamosHaven** [comment]
@lwt-pressy - Hi, thanks for the reply. I call the dmarcts-report-parser.pl by using the ./dmarcts-report-parser.pl command while in the dmarcts-report-parser directory.

Here is the debug report:

**root@dmarc-VirtualBox:~/dmarcts-report-parser# ./dmarcts-report-parser.pl -i -d
use tls with verify servercert.
Started at Thu Sep 21 09:05:33 2017
Using Mail::IMAPClient version 3.39 on perl 5.022001
Connecting with IO::Socket::INET PeerAddr imap-mail.outlook.com:143 PeerPort 143 Proto tcp Timeout 600 Debug 1
Connected to imap-mail.outlook.com:143
Read: 	* OK The Microsoft Exchange IMAP4 service is ready. [VgBJADEAUABSADAANAAwADEAQwBBADAAMAAwADUALgBlAHUAcgBwAHIAZAAwADQALgBwAHIAbwBkAC4AbwB1AHQAbABvAG8AawAuAGMAbwBtAA==]
Sending: 1 STARTTLS
Sent 12 bytes
Read: 	1 OK Begin TLS negotiation now.
Sending: 2 LOGIN dmarc-report-tester@outlook.com [Redact: Count=2 Showcredentials=OFF]
Sent 53 bytes
Read: 	2 OK LOGIN completed.
Sending: 3 STATUS Inbox (MESSAGES)
Sent 27 bytes
Read: 	* STATUS Inbox (MESSAGES 6) 
  	3 OK STATUS completed.
Processing 6 messages in folder <Inbox>.
Sending: 4 STATUS Inbox (MESSAGES)
Sent 27 bytes
Read: 	* STATUS Inbox (MESSAGES 6) 
  	4 OK STATUS completed.
Sending: 5 SELECT Inbox
Sent 16 bytes
Read: 	* 6 EXISTS
  	* 0 RECENT
  	* FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
  	* OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags
  	* OK [UIDVALIDITY 14] UIDVALIDITY value
  	* OK [UIDNEXT 50] The next unique identifier value
  	5 OK [READ-WRITE] SELECT completed.
Sending: 6 UID SEARCH ALL
Sent 18 bytes
Read: 	* SEARCH 34 35 36 37 38 41
  	6 OK SEARCH completed.
Sending: 7 CAPABILITY
Sent 14 bytes
Read: 	* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
  	7 OK CAPABILITY completed.
Sending: 8 UID FETCH 34 BODY[]
Sent 23 bytes
LITERAL: received literal in line * 1 FETCH (BODY[]  of length 81873; attempting to retrieve from the 4069 bytes in: Received: from SN1NAM02HT205.eop-nam02.prod.protection.outlook.com
   (2603:10a6:3:bd::31) by HE1P190MB0217.EURP190.PROD.OUTLOOK.COM with HTTPS via
   HE1PR0802CA0021.EURPRD08.PROD.OUTLOOK.COM; Wed, 20 Sep 2017 13:05:24 +0000
  Received: from SN1NAM02FT063.eop-nam02.prod.protection.outlook.com
   (10.152.72.54) by SN1NAM02HT205.eop-nam02.prod.protection.outlook.com
   (10.152.73.235) with Microsoft SMTP Server (version=TLS1_2,
   cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id 15.20.35.14; Wed, 20
   Sep 2017 13:05:23 +0000
  Authentication-Results: spf=pass (sender IP is <removed for security purposes>)
   smtp.mailfrom=<removed for security purposes>; outlook.com; dkim=none (message not signed)
   header.d=none;outlook.com; dmarc=pass action=none
   header.from=<removed for security purposes>;
  Received-SPF: Pass (protection.outlook.com: domain of <removed for security purposes>
   designates <removed for security purposes> as permitted sender)
   receiver=protection.outlook.com; client-ip=<removed for security purposes>;
   helo=mail1.bemta3.messagelabs.com;
  Received: from mail1.bemta3.messagelabs.com (<removed for security purposes>) by
   SN1NAM02FT063.mail.protection.outlook.com (<removed for security purposes>) with Microsoft SMTP
   Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id
   15.20.35.14 via Frontend Transport; Wed, 20 Sep 2017 13:05:22 +0000
  X-IncomingTopHeaderMarker: OriginalChecksum:81746D0F3AC69DA7FC9A466F604AF578813001DE91593A73DF46C23E48BFEEB2;UpperCasedChecksum:41AD51A027F05B37962ED1089E872F4C0AD87561333D7D9E99B9CE0BC332B457;SizeAsReceived:1495;Count:26
  Return-Path: <removed for security purposes>
  Received: from [<removed for security purposes>] by server-14.bemta-3.messagelabs.com id 44/8C-01910-19762C95; Wed, 20 Sep 2017 13:05:21 +0000
  X-Env-Sender: <removed for security purposes>
  X-Msg-Ref: <removed for security purposes>
  X-Originating-IP: [<removed for security purposes>]
  X-StarScan-Received:
  X-StarScan-Version: 9.4.45; banners=-,-,-
  X-VirusChecked: Checked
  Received: (qmail 13911 invoked from network); 20 Sep 2017 13:05:19 -0000
  Received: from <removed for security purposes> (HELO <removed for security purposes>) (<removed for security purposes>)
    by server-15.tower-33.messagelabs.com with DHE-RSA-AES128-SHA encrypted SMTP; 20 Sep 2017 13:05:19 -0000
  From: <removed for security purposes>
  To: <dmarc-report-tester@outlook.com>
  Subject: FW: DMARC Failure report for <removed for security purposes> Mail-From:
   IP:<removed for security purposes>
  Thread-Topic: DMARC Failure report for <removed for security purposes> Mail-From:
   IP:<removed for security purposes>
  Thread-Index: AQHTLb1Fx69z95xm20etwwHAZL4PFqK9xrBg
  Date: Wed, 20 Sep 2017 13:05:17 +0000
  Message-ID: <2F426823F7E91144A9C105D66A54D46C1A2D97@IRM75213.USERDOMAIN01.DOMROOT.INTERNAL>
  References: <FE.A4.12521.3E42BB95@mail313.prod.linkedin.com>
  In-Reply-To: <FE.A4.12521.3E42BB95@mail313.prod.linkedin.com>
  Accept-Language: en-GB, en-US
  Content-Language: en-US
  X-MS-Has-Attach: yes
  X-MS-TNEF-Correlator:
  x-originating-ip: [10.0.44.148]
  Content-Type: multipart/mixed;
  	boundary="_003_2F426823F7E91144A9C105D66A54D46C1A2D97IRM75213USERDOMAI_"
  X-IncomingHeaderCount: 26
  X-MS-Exchange-Organization-Network-Message-Id: 4625b612-e803-42c9-4205-08d5002840e5
  X-EOPAttributedMessage: 0
  X-EOPTenantAttributedMessage: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa:0
  X-MS-Exchange-Organization-MessageDirectionality: Incoming
  X-Microsoft-Exchange-Diagnostics: 1;SN1NAM02FT063;1:c4HB32BbgYHxYgiGF0eyhDMLDLTVjMvk80zA9JSJJzdJVCIm5a78QTjem4WBByJImb/qqXsfOoK/5Oz3O6cwKv/n3BVx6717oQ8eTdqGVOXoMOu32RZij47/aJD7ungX
  X-Forefront-Antispam-Report: EFV:NLI;SFV:NSPM;SFS:(98901004);DIR:INB;SFP:;SCL:1;SRVR:SN1NAM02HT205;H:mail1.bemta3.messagelabs.com;FPR:;SPF:None;LANG:;
  X-MS-Exchange-Organization-AuthSource: SN1NAM02FT063.eop-nam02.prod.protection.outlook.com
  X-MS-Exchange-Organization-AuthAs: Anonymous
  X-MS-PublicTrafficType: Email
  X-MS-Office365-Filtering-Correlation-Id: 4625b612-e803-42c9-4205-08d5002840e5
  X-Microsoft-Antispam: BCL:0;PCL:0;RULEID:(300000500095)(300135000095)(300000501095)(300135300095)(22001)(23075)(300000502095)(300135100095)(5000083)(610149)(650150)(8291501071);SRVR:SN1NAM02HT205;
  X-Microsoft-Exchange-Diagnostics: 1;SN1NAM02HT205;3:ni<END_OF_iBuffer>
Received ret=12288 16357 of 81873
Received ret=27 16384 of 81873
Received ret=16384 32768 of 81873
Received ret=16384 49152 of 81873
Received ret=16384 65536 of 81873
Received ret=16337 81873 of 81873
Read: 	* 1 FETCH (BODY[] 	 UID 34 FLAGS (\Seen))
  	8 OK FETCH completed.
Sending: 9 UID FETCH 34 (RFC822.SIZE)
Sent 30 bytes
Read: 	* 1 FETCH (RFC822.SIZE 119613 UID 34)
Read: 	9 OK FETCH completed.
ERROR: message_string() expected 119613 bytes but received 81873 you may need the IgnoreSizeErrors option at /usr/local/share/perl/5.22.1/Mail/IMAPClient.pm line 874.
	Mail::IMAPClient::message_string(Mail::IMAPClient=HASH(0x1fbcdd0), 34) called at ./dmarcts-report-parser.pl line 265

----------------------------------------------------------------
Processing IMAP message with UID #34 
----------------------------------------------------------------
parse_data: No data passed at ./dmarcts-report-parser.pl line 439.**


Update: I have had to edit and remove the personal information for security reasons, hope this does not effect your analysis. Cheers

**Comment by lwt-pressy** [comment]
@SamosHaven 

starting from line 230:
```
	my $imap = Mail::IMAPClient->new( Server => $imapserver,
		Ssl => $imapssl,
		Starttls => $imapopt,
		User => $imapuser,
		Password => $imappass,
		Debug=> $debug
  )
```

please change it to:
```
	my $imap = Mail::IMAPClient->new( Server => $imapserver,
		Ssl => $imapssl,
		Starttls => $imapopt,
		User => $imapuser,
		Password => $imappass,
		Ignoresizeerrors => 1,
		Debug=> $debug
  )
```

by adding line:
```
		Ignoresizeerrors => 1,
```

Don't forget the coma at the end. If this work, I'll add an Option for it to activate. Before I'll like to know if its work. The Reason I guess is a know bug in Microsoft.

**Comment by SamosHaven** [comment]
Yep that fixed it thank you. Wonder if you can help me with my next issue?

I'm trying to run dmarcts-report-viewer on my local host set up using apache2. I have moved the dmarcts report-parser folder along with all the other files into the /var/www/html directory. My issue is that when I direct the browser to 127.0.0.1/dmarcts-report-parser/dmarcts-report-viewer/dmarcts-report-viewer.php, it shows a blank white web page. 

I know the directory is correctly linked to the php file as I removed the <?php tag and the same web page displayed all the code in the file, but it wont display the SQL database. 

I have also checked my SQL database on my localhost and it is populated using dmarcts-report-parser.

Cheers

**Comment by lwt-pressy** [comment]
@SamosHaven, thx for the feedback. I will prepare a new commit soon, where this can be set in the config file.

As for the Error, would you please me a new issue in dmarcts-report-viewer. So we can handle this seperately. In your case it would help if you include an error log of your apache server where normally an error is seen. It probaly in /var/log/apache or /var/log/http{d}, depending on your distro or your config file.

**Comment by lwt-pressy** [comment]
@SamosHaven - today everythings goes fast. The new version is merge. Please update your package and use the new config sample, especially the new option "$imapignoreerror = 1;"  (you need 1 here).

If it fixes it give us feedback so this issue can be closed.
