### ISSUE TITLE
tar.gz and txt attachments

### ISSUE THREAD

**Issue by mrveiss** [techsneeze/dmarcts-report-parser#42]
Hello,
Some attached reports comes in tar.gz, some in xml.gz format some in plain txt file
[proximus.be!gemoss.lv!1506937803!1507024204.xml.gz](https://github.com/techsneeze/dmarcts-report-parser/files/1354923/proximus.be.gemoss.lv.1506937803.1507024204.xml.gz)
the import script should be able to import them, or at least skip them, because when it meets the message with one of those attached, it stops, and cant process further messages.

**Comment by techsneeze** [comment]
I have been unable to reproduce this.  You may be missing a dependency that is not allowing the script to uncompress those files.
