### ISSUE TITLE
Could not find an embedded ZIP!

### ISSUE THREAD

**Issue by michaelschefczyk** [techsneeze/dmarcts-report-parser#50]
Dear All,

My aim is to automate dmarc report processing by parsing reports from an exchangeserver based mailbox. Unfortunately, this does fail. I am able to parse unzipped xml files from a folder but neither zipped reports from a folder nor from IMAP.

On Centos 7, the debug report does contain two noticeable errors per message:

Could not find an embedded ZIP! The IMAP message with UID #29 does not seem to contain a valid DMARC report. Skipped.                      

ERROR: message_string() expected 1791 bytes but received 3546 you may need the IgnoreSizeErrors option at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 869

On Debian stretch, only the second error does occur.

Moving the messages to "Inbox.processed" does work on Centos but not on Debian?

I am certainly not a perl expert.

Could you please be so kind as to point me to possible next steps?

Regards,

Michael Schefczyk

**Comment by shiz0** [comment]
Those "two" errors are related. 
There's also an Option for that at line 22 of the config file.
Setting this to '1' fixed it for me, reports are flowing in now....

**Comment by michaelschefczyk** [comment]
Thank you! The description on line 22 might have been too obvious :)

**Comment by shiz0** [comment]
Was for me, too. :-D 
I only found it after I dug around in the code and discovered that its read from the config file. :1st_place_medal:
