### ISSUE TITLE
run as cron

### ISSUE THREAD

**Issue by Tntdruid** [techsneeze/dmarcts-report-parser#52]
Hello,

Any way to run the script as cron job?

**Comment by lwt-pressy** [comment]
hi, the script can be run by cron as any script. Nothing special needed. Here my crontab entry:

# ------------------------- update dmarc --------------------------------------
*/30    *       *       *       *       ~/Source/dmarc/dmarcts-report-parser/dmarcts-report-parser.pl -i -r

**Comment by Tntdruid** [comment]
Thanks, Using 
0 */1 * * * perl /root/dmarcts/dmarcts-report-parser/dmarcts-report-parser.pl -i -r > /dev/null 2>&1
