### ISSUE TITLE
Skipping Zip file

### ISSUE THREAD

**Issue by K4S1** [techsneeze/dmarcts-report-parser#58]
Hi I had a zip file skipped for some reason

I see this in debug:

MimeType: multipart/mixed
This is a multipart attachment
Skipped an unknown attachment (text/plain)
Skipped an unknown attachment (application/x-gzip)
Could not find an embedded ZIP! The IMAP message with UID #133 does not seem to contain a valid DMARC report. Skipped.

Does this make sense ?

**Comment by techsneeze** [comment]
This seems odd, as I'm seeing plenty of zip attachments processing without issue.  It seems unable to detect the attachment, but not clear why.  Were you able to figure it out?  Is it only one specific sender?  Multiple senders?

**Comment by K4S1** [comment]
It seems like the code do not accept the x-gzip as I read it.
But only gzip
Guess that is the reason i see unknown attachment (application/x-gzip)
I have 5-6 spamfilters that send me in that format.

**Comment by Clete2** [comment]
Yahoo causes this issue for me.
