### ISSUE TITLE
Make this project ready for inclusion into Debian

### ISSUE THREAD

**Issue by sunweaver** [techsneeze/dmarcts-report-parser#67]
Hi,

while setting up Rspamd with SPD/DKIM/DMARC on my own mail server recently, I today stumbled over this project. I have deployed it right a away and its awesome as it is simple to setup. Nice work!

Would you mind me to upload this package to Debian? If not, then I'd like to ask you for a release of the current code base (if it is releasable).

Thanks+Greets
Mike (aka sunweaver at debian.org)

**Comment by williamdes** [comment]
https://ftp-master.debian.org/new/dmarcts-report-parser_1.0+git20190809.1.bb5dd8b6-2.html

**Comment by techsneeze** [comment]
Awesome!  Thanks for publishing it and I'm appreciative.  Consider permission granted.  :)
