### ISSUE TITLE
If dmarc reports are not in a subfolder of the inbox

### ISSUE THREAD

**Issue by beppe9000** [techsneeze/dmarcts-report-parser#70]
I receive dmarc reports in the inbox. what do I set $imapreadfolder to ?

**Comment by lxsinfo** [comment]
Depends on your mail setup, on my setup it would work with:
$imapreadfolder   = 'INBOX';

**Comment by techsneeze** [comment]
As was mentioned earlier, it depends greatly on your IMAP server.  I've seen "Inbox", "INBOX", and I think "mail.Inbox".
