### ISSUE TITLE
SPF alignment pass/fail

### ISSUE THREAD

**Issue by bubbleg5** [techsneeze/dmarcts-report-parser#73]
I recently installed your project. but I realized it doesn't load the SPF Alignment field.
Is it a bug or doesn't it detect the tag?

https://mxtoolbox.com/DmarcReportAnalyzer.aspx?id=F-990c6c3d-e57e-4d7e-a462-ddf683a53ae1

[yahoo.com!laurinzbabuin.com!1586563200!1586649599.xml.zip](https://github.com/techsneeze/dmarcts-report-parser/files/4466610/yahoo.com.laurinzbabuin.com.1586563200.1586649599.xml.zip)

**Comment by techsneeze** [comment]
The submitted issue is against the parser, but perhaps you are concerned on how the output is portrayed in the viewer portion?  
From a viewer perspective, It displays the auth results sections of the report, as well as the overall policy disposition.  When I imported the provided record, it does display that as expected.  The overall view is a bit different than what mxtoolbox is showing.  The additional fields are being imported into the database though, if you are using a different method to view/query the data.
