### ISSUE TITLE
DBD::mysql::db do failed: Multiple primary key defined 

### ISSUE THREAD

**Issue by upengan78** [techsneeze/dmarcts-report-parser#75]
Hi, I am thankful for this great little tool. Helped a lot. 
Since yesterday I noticed my imap emails were not being read from my routine script so when I run it manually today I notice following messages.

```

DBD::mysql::db do failed: Multiple primary key defined at /root/dmarcts-report-parser/dmarcts-report-parser.pl line 983.
DBD::mysql::db do failed: Incorrect datetime value: '1969-12-31 18:00:00' for column 'mindate' at row 1 at /root/dmarcts-report-parser/dmarcts-report-parser.pl line 770.
Cannot add report to database (Incorrect datetime value: '1969-12-31 18:00:00' for column 'mindate' at row 1). Skipped.
Skipping IMAP message with UID #10605 due to database errors.
DBD::mysql::db do failed: Incorrect datetime value: '1969-12-31 18:00:00' for column 'mindate' at row 1 at /root/dmarcts-report-parser/dmarcts-report-parser.pl line 770.
Cannot add report to database (Incorrect datetime value: '1969-12-31 18:00:00' for column 'mindate' at row 1). Skipped.
Skipping IMAP message with UID #10611 due to database errors.
Not a HASH reference at /root/dmarcts-report-parser/dmarcts-report-parser.pl line 720.
```

What could be causing these messages all of a sudden? Thank you,
UG

**Comment by upengan78** [comment]
I noticed some already processed emails were put in to the folder the script was scanning for. This was my personal filter in gmail that goofed up the emails and put already processed emails again in the inbox. When I deleted those old emails, script is working is working now with following output

```
perl /root/dmarcts-report-parser/dmarcts-report-parser.pl -i
DBD::mysql::db do failed: Multiple primary key defined at /root/dmarcts-report-parser/dmarcts-report-parser.pl line 983.
Skipping storage of large XML (493658 bytes) as defined in config file.
Use of uninitialized value $message in substitution (s///) at /root/dmarcts-report-parser/dmarcts-report-parser.pl line 492.
parse_data: No data passed at /root/dmarcts-report-parser/dmarcts-report-parser.pl line 497.
```

**Comment by Tntdruid** [comment]
i'm getting this today:

DBD::mysql::db do failed: Data truncated for column 'dkimresult' at row 1 at dmarcts-report-parser/dmarcts-report-parser.pl line 720.
Had the script working for years.

**Comment by techsneeze** [comment]
Were you able to find any more information on this?  Is it on a specific message?  I'd suggest moving that message to another folder, and see if there is something about it confusing it.

**Comment by Tntdruid** [comment]
I delete it, its only reports from yahoo there does that.

**Comment by techsneeze** [comment]
Thanks, I'll keep an eye out for some Yahoo ones.  I haven't come across this yet in my own system.  Perhaps they made some changes recently?

**Comment by Tntdruid** [comment]
@techsneeze got some from yahoo today, works like normal.

**Comment by techsneeze** [comment]
Closing since it sounds like it is working as desired now!
