### ISSUE TITLE
FYI: forked a postgres version

### ISSUE THREAD

**Issue by grinapo** [techsneeze/dmarcts-report-parser#76]
Hello,

If anyone's interested I have forked and changed a postgres version at https://github.com/grinapo/dmarcts-report-parser

Almost identical except:
* some cleanup and db generalisations
* removed automated table generation (little value for lot of time for me)

Feel free to pull back ideas if interested. :)

Also do whatever you please with this non-issue.

Thanks for the code!

**Comment by techsneeze** [comment]
Thanks for letting me know! I'm glad you found it useful.  I'm totally open to pull-requests, if you want to go that route.
