### ISSUE TITLE
Parser does not process content-type:multipart/related emails

### ISSUE THREAD

**Issue by trogper** [techsneeze/dmarcts-report-parser#77]
Domain seznam.cz generates report emails with text and an attachment with content-type 'multipart/related'.
The script outputs `Could not find an embedded ZIP!`, as it does not process all parts.
I suppose we just need to change `lc $mtype eq "multipart/mixed"` to `lc $mtype eq "multipart/mixed" or lc $mtype eq "multipart/related"`, but I can not test it as I currently have no such report emails (outlook converted all of them to "multipart/mixed")

**Comment by techsneeze** [comment]
Have you tested the code change?  If so, feel free to submit a Pull Request!

**Comment by techsneeze** [comment]
Just submitted a small change that should accommodate these situations.  Please try it out!

**Comment by trogper** [comment]
will try out, thanks

**Comment by techsneeze** [comment]
Closing for now, since it is expected to have been fixed.
