### ISSUE TITLE
Parser not working

### ISSUE THREAD

**Issue by zezekim** [techsneeze/dmarcts-report-parser#93]
Hello,

Thanks for this wonderful script. We have used it for years however we had to change servers and this one stopped working. I tried using an old perl version however I can't seem to make it work. Can you please take a look and kindly point me to the right direction?

Btw, I have renamed the script to run.pl as its shorter but the parser is intact and unmodified.

Thank you.

` Mail::IMAPClient::message_string('Mail::IMAPClient=HASH(0x210f240)', 11523) called at ./run.pl line 295
Could not find an embedded ZIP! The IMAP message with UID #11523 does not seem to contain a valid DMARC report. Skipped.
Trying command when NOT connected! at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 122.
        Mail::IMAPClient::LastError('Mail::IMAPClient=HASH(0x210f240)', 'NO not connected') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1493
        Mail::IMAPClient::_send_line('Mail::IMAPClient=HASH(0x210f240)', '227 STATUS notprocessed (MESSAGES)', 0) called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1320
        Mail::IMAPClient::_imap_command_do('Mail::IMAPClient=HASH(0x210f240)', 'STATUS notprocessed (MESSAGES)') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1225
        Mail::IMAPClient::_imap_command('Mail::IMAPClient=HASH(0x210f240)', 'STATUS notprocessed (MESSAGES)') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 2356
        Mail::IMAPClient::status('Mail::IMAPClient=HASH(0x210f240)', 'notprocessed') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1977
        Mail::IMAPClient::exists('Mail::IMAPClient=HASH(0x210f240)', 'notprocessed') called at ./run.pl line 419
        main::moveToImapFolder('Mail::IMAPClient=HASH(0x210f240)', 11523, 'notprocessed') called at ./run.pl line 316
Trying command when NOT connected! LastError was: NO not connected at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 122.
        Mail::IMAPClient::LastError('Mail::IMAPClient=HASH(0x210f240)', 'Error sending \'227 STATUS notprocessed (MESSAGES)\': NO not ...') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1321
        Mail::IMAPClient::_imap_command_do('Mail::IMAPClient=HASH(0x210f240)', 'STATUS notprocessed (MESSAGES)') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1225
        Mail::IMAPClient::_imap_command('Mail::IMAPClient=HASH(0x210f240)', 'STATUS notprocessed (MESSAGES)') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 2356
        Mail::IMAPClient::status('Mail::IMAPClient=HASH(0x210f240)', 'notprocessed') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1977
        Mail::IMAPClient::exists('Mail::IMAPClient=HASH(0x210f240)', 'notprocessed') called at ./run.pl line 419
        main::moveToImapFolder('Mail::IMAPClient=HASH(0x210f240)', 11523, 'notprocessed') called at ./run.pl line 316`

**Comment by techsneeze** [comment]
Have you ensured you have all the right perl modules installed?
Is it doing this on all messages or just one?

**Comment by techsneeze** [comment]
Closing until we have more info
